### ISSUE TITLE
how to sign daily tarballs?

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-infrastructure#2]
How to do this securely -- we need to sign so that launchpad accepts our request, but we would like to do this in a secure way. Passphrase prompts do not work in a scheduled cron job.

**Comment by davidelang** [comment]
There really is no fully secure way. Anything you do is going to require either 
a password that can be recreated with access to files and scrips, or blind 
trust.

Your current approach is blind trust.

you could put a passphrase in a file, split the passphrase between multiple 
files (including taking something from one file and doing processing on it, 
making your script doing the processing another file)

but the bottom line is that it really is turtles all the way down :-(

The best that I've seen (from a security point of view) has been to require that 
someone do something manually to bring things up, after which the sensitive data 
lives only in memory.

that's not saying that things can't be better than they currently are. Currently 
one item (the passprhaseless key) can be stolen and all signatures become 
untrusted. By adding additional layers we can make it so that multiple things 
would have to be known, making life more complex for the attacker.

But it all depends on what the threat is that we are trying to defend against.

David Lang

**Comment by rgerhards** [comment]
I would really like to avoid that manual action, because it will be lost at each reboot, and this is (experience tells) from where things go downhill... So it looks like I've used the current best solution and we should probably stick with it ... and hopefully keep an eye on which packages pop up on Launchpad. Also, periodic key changes probably wouldn't hurt ;)

Any objections on that?
